
export type ContentView = 
  | 'video' 
  | 'black' 
  | 'dunes' 
  | 'company' 
  | 'projects' 
  | 'gallery'
  | 'contact'
  | 'privacy'
  | 'terms'
  | 'cookie'
  | 'legal'
  | 'intellectual-property'
  | 'accessibility'
  | 'refund'
  | 'shipping'
  | 'terms-sale'
  | 'ugc'
  | 'data-retention'
  | 'cybersecurity'
  | 'ai-policy'
  | 'california-privacy'
  | 'do-not-sell'
  | 'ethics'
  | 'anti-bribery'
  | 'whistleblower'
  | 'supplier-code'
  | 'employee-code'
  | 'social-media'
  | 'environmental'
  | 'sitemap';

// Utility type to extract policy views from ContentView
export type PolicyView = Exclude<ContentView, 'video' | 'black' | 'dunes' | 'company' | 'projects' | 'gallery' | 'contact'>;
